[project]
name = "forastero-token"
description = "Fixed-supply fungible token for Forastero"
authors = ["Ebimyrriscap Ventures"]
telemetry = true
cache_dir = "./.cache"

[contracts.forastero-token]
path = "contracts/forastero-token.clar"

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false